---
# tasks file for azure-eventhub
- name: Create or Update instance of Event Hub
  azure_rm_eventhub:
    resource_group: "{{ resource_group }}"
    location: eastus
    namespace_name: "{{ item.namespace }}"
    name: "{{ item.name }}"
    tags:
      a: b
    sku: free