---
# tasks file for azure-keyvault
- name: Create or Update instance of Key Vault
  azure_rm_keyvault:
    resource_group: "{{ resource_group }}"
    vault_name: "{{ item.name }}"
    enabled_for_deployment: yes
    vault_tenant: "{{ tenant_id }}"
    sku:
      name: standard
    # access_policies:
    #   - tenant_id: 72f98888-8666-4144-9199-2d7cd0111111
    #     object_id: 99998888-8666-4144-9199-2d7cd0111111
    #     keys:
    #       - get
    #       - list