---
# tasks file for azure-keyvault
- name: Create or Update instance of Key Vault
  azure.azcollection.azure_rm_keyvault:
    resource_group: "{{ resource_group }}"
    vault_name: "{{ item.name }}"
    enabled_for_deployment: yes
    vault_tenant: "{{ tenant_id }}"
    sku:
      name: standard
    access_policies:
      - tenant_id: "{{ tenant_id }}"
        object_id: "5942e495-f8a1-480c-a777-dd588fa25c04"
        keys:
          - get
          - list